version: "3.3"
services:
    rendezvous:
        build: "./screensy-rendezvous"
        restart: unless-stopped
        ports: 
            - "4000:4000"
    website:
        build: "./screensy-website"
        restart: unless-stopped
    caddy:
        build: .
        restart: unless-stopped
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
    turn:
        image: "coturn/coturn:4.5.2"
        restart: unless-stopped
        # Use the host network directly as Docker performs badly with
        # large port ranges
        network_mode: "host"
        volumes:
            - ./turnserver.conf:/etc/coturn/turnserver.conf

volumes:
  caddy_data:
    external: true
  caddy_config:
